/** Kigali City districts eligible for home delivery. */
export const KIGALI_DELIVERY_DISTRICTS = ["Gasabo", "Nyarugenge", "Kicukiro"] as const;

export type KigaliDeliveryDistrict = (typeof KIGALI_DELIVERY_DISTRICTS)[number];

/**
 * Neighbourhoods, cells, and popular landmark-based areas by Kigali district.
 * Includes colloquial "kwa …" / "kuri …" names people use for directions.
 */
export const KIGALI_HOODS: Record<KigaliDeliveryDistrict, string[]> = {
  Gasabo: [
    // Cells & neighbourhoods
    "Bibare",
    "Bumbogo",
    "Busanza",
    "Bwiza",
    "Cyaruzinge",
    "Gatsata",
    "Gikomero",
    "Gisozi",
    "Gishushu",
    "Jabana",
    "Jali",
    "Kacyiru",
    "Kagugu",
    "Kamutwa",
    "Kibagabaga",
    "Kigabiro",
    "Kimironko",
    "Kinyinya",
    "Masaka",
    "Ndera",
    "Nduba",
    "Remera",
    "Rusororo",
    "Rutunga",
    "Ubumwe",
    "Urugwiro",
    // Well-known areas
    "Nyarutarama",
    "Akabuga ka Nyarutarama",
    "Kimihurura",
    "Gacuriro",
    "Batsinda",
    "Kisimenti",
    "Gisimenti",
    "Remera Gisimenti",
    "Kacyiru Ville",
    "Kinyinya Hill",
    "Kinyinya Centre",
    "Rwandex",
    "Ndera Hill",
    "Cyimana",
    "Kagarama",
    // Landmarks & popular reference points
    "Kuri Kingdom (Kigali Convention Centre)",
    "Kuri Kigali Convention Centre",
    "Kuri Kigali Heights",
    "Kuri UTC Kigali",
    "Kuri CHUK",
    "Kuri Amahoro Stadium",
    "Kuri Petit Stade",
    "Kuri Rwanda Revenue Authority (RRA)",
    "Kuri US Embassy",
    "Kuri Kacyiru Police HQ",
    "Kuri Simba Supermarket (Kimironko)",
    "Kuri Kigali Business Centre (KBC)",
    "Kuri Rwanda Development Board (RDB)",
    // Colloquial "kwa …" / "kuri …" areas
    "Kwa Rubangura",
    "Kwa Mushimire",
    "Kwa Gasasira",
    "Kwa Gisimenti",
    "Kwa Kimironko Market",
    "Kwa Remera",
    "Kwa Kibagabaga",
    "Kwa Kacyiru",
    "Kwa Gacuriro",
    "Kwa Batsinda",
    "Kwa Nyarutarama",
    "Kwa Kinyinya",
    "Kwa Ndera",
    "Kwa Gisozi",
    "Kwa Kagugu",
    "Kwa Kamutwa",
    "Kwa Gishushu",
    "Kwa Urugwiro",
    "Kwa Ubumwe",
    "Kwa Masaka",
    "Kwa Rusororo",
    "Kwa Rutunga",
    "Kwa Jali",
    "Kwa Jabana",
    "Kwa Gatsata",
    "Kwa Bumbogo",
    "Kwa Bibare",
    "Kwa Nduba",
    "Kwa Gikomero",
    "Kwa Cyaruzinge",
    "Kwa Busanza",
    "Kwa Bwiza",
    "Kwa Kimihurura",
    "Kwa Kisimenti",
    "Kwa Rwandex",
    "Kwa Kagarama",
    "Kuri Remera",
    "Kuri Kimironko",
    "Kuri Kibagabaga",
    "Kuri Kimihurura",
    "Kuri Gacuriro",
    "Kuri Nyarutarama",
    "Kuri Kisimenti",
    "Kuri Rwandex",
    "Kuri Ndera",
    "Kuri Gisozi",
    "Kuri Kinyinya",
    "Kuri Batsinda",
    "Kuri Kagarama",
    // Main roads (Gasabo)
    "KG 1 Ave",
    "KG 5 Ave",
    "KG 7 Ave",
    "KG 9 Ave",
    "KG 11 Ave",
    "KG 13 Ave",
    "KG 15 Ave",
    "KG 17 Ave",
    "KG 19 Ave",
    "KG 21 Ave",
    "KG 23 Ave",
    "KG 25 Ave",
    "KN 3 Rd",
    "KN 5 Rd",
    "KN 7 Rd",
    "KN 9 Rd",
  ],
  Nyarugenge: [
    // Cells & neighbourhoods
    "Biryogo",
    "Cyivugiza",
    "Gitega",
    "Kamenge",
    "Kanyinya",
    "Kigali",
    "Kimisagara",
    "Kiyovu",
    "Mageregere",
    "Mageragere",
    "Muhima",
    "Mumena",
    "Nyakabanda",
    "Nyamirambo",
    "Nyarugenge",
    "Rugenge",
    "Rwampara",
    "Rwezamenyo",
    "Rugano",
    // Well-known areas
    "City Centre",
    "Downtown Kigali",
    "CBD Kigali",
    "Nyabugogo",
    "Cyahafi",
    "Kiyovu I",
    "Kiyovu II",
    "Kiyovu III",
    "Kiyovu IV",
    "Akabuga ka Nyamirambo",
    "Akabuga ka Kimisagara",
    "Akabuga ka Nyakabanda",
    "Akabuga ka Muhima",
    "Giporoso",
    // Landmarks & popular reference points
    "Kuri Mille Collines",
    "Kuri Hôtel des Mille Collines",
    "Kuri Serena Hotel",
    "Kuri KBC (Kigali Business Centre)",
    "Kuri Nyabugogo Taxi Park",
    "Kuri Nyabugogo Bus Park",
    "Kuri Kigali City Tower",
    "Kuri CHIC Building",
    "Kuri Kigali City Market",
    "Kuri Simba Supermarket (Muhima)",
    "Kuri Kigali Genocide Memorial",
    "Kuri Stade Amahoro (Nyabugogo side)",
    "Kuri Rwanda Convention Bureau",
    // Colloquial "kwa …" / "kuri …" areas
    "Kwa Nyamirambo",
    "Kwa Kimisagara",
    "Kwa Nyakabanda",
    "Kwa Muhima",
    "Kwa Nyabugogo",
    "Kwa Biryogo",
    "Kwa Gitega",
    "Kwa Kanyinya",
    "Kwa Kiyovu",
    "Kwa Mageregere",
    "Kwa Mageragere",
    "Kwa Rwezamenyo",
    "Kwa Rugenge",
    "Kwa Rwampara",
    "Kwa Cyivugiza",
    "Kwa Kamenge",
    "Kwa Mumena",
    "Kwa Rugano",
    "Kwa Nyarugenge",
    "Kwa Cyahafi",
    "Kwa Nyamvumba",
    "Kwa Mushimire",
    "Kwa Giporoso",
    "Kuri Nyamirambo",
    "Kuri Kimisagara",
    "Kuri Nyakabanda",
    "Kuri Muhima",
    "Kuri Nyabugogo",
    "Kuri Biryogo",
    "Kuri Gitega",
    "Kuri Kanyinya",
    "Kuri Kiyovu",
    "Kuri Mageregere",
    "Kuri Mageragere",
    "Kuri Rwezamenyo",
    "Kuri Rugenge",
    "Kuri Rwampara",
    "Kuri Cyivugiza",
    "Kuri Kamenge",
    "Kuri Mumena",
    "Kuri Rugano",
    "Kuri Nyarugenge",
    "Kuri Cyahafi",
    "Kuri City Centre",
    "Kuri Downtown",
    // Main roads (Nyarugenge / city centre)
    "KN 2 St",
    "KN 4 Ave",
    "KN 6 Ave",
    "KN 8 Ave",
    "KN 10 Ave",
    "KN 12 Ave",
    "KN 14 Ave",
    "KN 16 Ave",
    "KN 18 Ave",
    "KN 20 Ave",
    "KN 22 Ave",
    "KN 24 Ave",
    "KN 26 Ave",
    "KN 28 Ave",
    "KN 30 Ave",
    "KN 32 Ave",
    "KN 34 Ave",
    "KN 36 Ave",
    "KN 38 Ave",
    "KN 40 Ave",
    "KN 42 Ave",
    "KN 44 Ave",
    "KN 46 Ave",
    "KN 48 Ave",
    "KN 50 Ave",
    "KN 52 Ave",
    "KN 54 Ave",
    "KN 56 Ave",
    "KN 58 Ave",
    "KN 60 Ave",
    "KN 62 Ave",
    "KN 64 Ave",
    "KN 66 Ave",
    "KN 68 Ave",
    "KN 70 Ave",
    "KN 72 Ave",
    "KN 74 Ave",
    "KN 76 Ave",
    "KN 78 Ave",
    "KN 80 Ave",
    "KN 82 Ave",
    "KN 84 Ave",
    "KN 86 Ave",
    "KN 88 Ave",
    "KN 90 Ave",
    "KN 92 Ave",
    "KN 94 Ave",
    "KN 96 Ave",
    "KN 98 Ave",
    "KN 100 Ave",
  ],
  Kicukiro: [
    // Cells & neighbourhoods
    "Gahanga",
    "Gatenga",
    "Gikondo",
    "Gikondo Industrial",
    "Kabeza",
    "Kagarama",
    "Kanombe",
    "Kicukiro",
    "Kicukiro Centre",
    "Kigarama",
    "Masaka",
    "Niboye",
    "Nyarurama",
    "Rebero",
    "Rukiri",
    "Rwampara",
    "Sonatubes",
    "Zinia",
    // Well-known areas
    "Nyarutarama (Kicukiro side)",
    "Akabuga ka Gatenga",
    "Akabuga ka Gikondo",
    "Akabuga ka Kanombe",
    "Akabuga ka Nyarurama",
    "Kanombe Airport area",
    "Rebero Hill",
    "Gikondo Expo Grounds",
    "Sonatube Industrial",
    "Zinia Industrial",
    "Giporoso (Kicukiro side)",
    // Landmarks & popular reference points
    "Kuri Kanombe Airport",
    "Kuri Expo Grounds Gikondo",
    "Kuri Sonatube",
    "Kuri Kicukiro Market",
    "Kuri Kabeza Market",
    "Kuri Gahanga",
    "Kuri Rebero Hill",
    "Kuri Zinia",
    "Kuri Rwanda Military Hospital (Kanombe)",
    // Colloquial "kwa …" / "kuri …" areas
    "Kwa Gikondo",
    "Kwa Gatenga",
    "Kwa Kanombe",
    "Kwa Kabeza",
    "Kwa Kagarama",
    "Kwa Kicukiro",
    "Kwa Niboye",
    "Kwa Nyarurama",
    "Kwa Rebero",
    "Kwa Rukiri",
    "Kwa Rwampara",
    "Kwa Gahanga",
    "Kwa Masaka",
    "Kwa Sonatubes",
    "Kwa Zinia",
    "Kwa Kigarama",
    "Kwa Nyamvumba",
    "Kwa Mushimire",
    "Kwa Giporoso",
    "Kuri Gikondo",
    "Kuri Gatenga",
    "Kuri Kanombe",
    "Kuri Kabeza",
    "Kuri Kagarama",
    "Kuri Kicukiro",
    "Kuri Niboye",
    "Kuri Nyarurama",
    "Kuri Rebero",
    "Kuri Rukiri",
    "Kuri Rwampara",
    "Kuri Gahanga",
    "Kuri Masaka",
    "Kuri Sonatubes",
    "Kuri Zinia",
    "Kuri Kigarama",
    // Main roads (Kicukiro)
    "KK 1 Ave",
    "KK 3 Ave",
    "KK 5 Ave",
    "KK 7 Ave",
    "KK 9 Ave",
    "KK 11 Ave",
    "KK 13 Ave",
    "KK 15 Ave",
    "KK 17 Ave",
    "KK 19 Ave",
    "KK 21 Ave",
    "KK 23 Ave",
    "KK 25 Ave",
    "KK 27 Ave",
    "KK 29 Ave",
    "KK 31 Ave",
  ],
};

export function hoodsForDistrict(district: string): string[] {
  if (!district) return [];
  const key = KIGALI_DELIVERY_DISTRICTS.find(
    (d) => d.toLowerCase() === district.toLowerCase(),
  );
  if (!key) return [];
  return [...new Set(KIGALI_HOODS[key])].sort((a, b) => a.localeCompare(b));
}

export function isKigaliDeliveryDistrict(district: string): boolean {
  return KIGALI_DELIVERY_DISTRICTS.some(
    (d) => d.toLowerCase() === district.toLowerCase(),
  );
}
