"""add_hospital_admin_profiles

Revision ID: 3e4bafd4598b
Revises: f892943f1fdb
Create Date: 2026-05-22 23:42:05.448979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e4bafd4598b'
down_revision: Union[str, None] = 'f892943f1fdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospital_admin_profiles',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('hospital_id', sa.String(), nullable=False),
    sa.Column('position_title', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospital_admin_profiles_hospital_id'), 'hospital_admin_profiles', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_hospital_admin_profiles_user_id'), 'hospital_admin_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hospital_admin_profiles_user_id'), table_name='hospital_admin_profiles')
    op.drop_index(op.f('ix_hospital_admin_profiles_hospital_id'), table_name='hospital_admin_profiles')
    op.drop_table('hospital_admin_profiles')
    # ### end Alembic commands ###
