"""
Direct table creation script — bypasses Alembic's autogenerated migration
ordering issues by letting SQLAlchemy resolve dependencies itself.
Run from farumasi_api/: python scripts/create_tables.py
"""
import asyncio
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

from sqlalchemy.ext.asyncio import create_async_engine
from app.core.config import settings
import app.models  # noqa — registers all models against Base
from app.models.base import Base


async def create_all_tables():
    engine = create_async_engine(settings.ASYNC_DATABASE_URL, echo=True)
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
    await engine.dispose()
    print("\n✓ All tables created successfully.")


if __name__ == "__main__":
    asyncio.run(create_all_tables())
